package com.gk.model;

import java.util.ArrayList;
import java.util.List;

public class ArriveExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public ArriveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUuidIsNull() {
            addCriterion("uuid is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("uuid is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("uuid =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("uuid <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("uuid >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("uuid >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("uuid <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("uuid <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("uuid like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("uuid not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("uuid in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("uuid not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("uuid between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("uuid not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(String value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(String value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(String value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(String value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLike(String value) {
            addCriterion("company_id like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotLike(String value) {
            addCriterion("company_id not like", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<String> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<String> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNull() {
            addCriterion("version_no is null");
            return (Criteria) this;
        }

        public Criteria andVersionNoIsNotNull() {
            addCriterion("version_no is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNoEqualTo(Integer value) {
            addCriterion("version_no =", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotEqualTo(Integer value) {
            addCriterion("version_no <>", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThan(Integer value) {
            addCriterion("version_no >", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("version_no >=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThan(Integer value) {
            addCriterion("version_no <", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoLessThanOrEqualTo(Integer value) {
            addCriterion("version_no <=", value, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoIn(List<Integer> values) {
            addCriterion("version_no in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotIn(List<Integer> values) {
            addCriterion("version_no not in", values, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoBetween(Integer value1, Integer value2) {
            addCriterion("version_no between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andVersionNoNotBetween(Integer value1, Integer value2) {
            addCriterion("version_no not between", value1, value2, "versionNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNull() {
            addCriterion("batch_no is null");
            return (Criteria) this;
        }

        public Criteria andBatchNoIsNotNull() {
            addCriterion("batch_no is not null");
            return (Criteria) this;
        }

        public Criteria andBatchNoEqualTo(String value) {
            addCriterion("batch_no =", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotEqualTo(String value) {
            addCriterion("batch_no <>", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThan(String value) {
            addCriterion("batch_no >", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoGreaterThanOrEqualTo(String value) {
            addCriterion("batch_no >=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThan(String value) {
            addCriterion("batch_no <", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLessThanOrEqualTo(String value) {
            addCriterion("batch_no <=", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoLike(String value) {
            addCriterion("batch_no like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotLike(String value) {
            addCriterion("batch_no not like", value, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoIn(List<String> values) {
            addCriterion("batch_no in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotIn(List<String> values) {
            addCriterion("batch_no not in", values, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoBetween(String value1, String value2) {
            addCriterion("batch_no between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andBatchNoNotBetween(String value1, String value2) {
            addCriterion("batch_no not between", value1, value2, "batchNo");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeIsNull() {
            addCriterion("dest_longgitude is null");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeIsNotNull() {
            addCriterion("dest_longgitude is not null");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeEqualTo(String value) {
            addCriterion("dest_longgitude =", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeNotEqualTo(String value) {
            addCriterion("dest_longgitude <>", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeGreaterThan(String value) {
            addCriterion("dest_longgitude >", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeGreaterThanOrEqualTo(String value) {
            addCriterion("dest_longgitude >=", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeLessThan(String value) {
            addCriterion("dest_longgitude <", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeLessThanOrEqualTo(String value) {
            addCriterion("dest_longgitude <=", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeLike(String value) {
            addCriterion("dest_longgitude like", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeNotLike(String value) {
            addCriterion("dest_longgitude not like", value, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeIn(List<String> values) {
            addCriterion("dest_longgitude in", values, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeNotIn(List<String> values) {
            addCriterion("dest_longgitude not in", values, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeBetween(String value1, String value2) {
            addCriterion("dest_longgitude between", value1, value2, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLonggitudeNotBetween(String value1, String value2) {
            addCriterion("dest_longgitude not between", value1, value2, "destLonggitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeIsNull() {
            addCriterion("dest_latitude is null");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeIsNotNull() {
            addCriterion("dest_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeEqualTo(String value) {
            addCriterion("dest_latitude =", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeNotEqualTo(String value) {
            addCriterion("dest_latitude <>", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeGreaterThan(String value) {
            addCriterion("dest_latitude >", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("dest_latitude >=", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeLessThan(String value) {
            addCriterion("dest_latitude <", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeLessThanOrEqualTo(String value) {
            addCriterion("dest_latitude <=", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeLike(String value) {
            addCriterion("dest_latitude like", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeNotLike(String value) {
            addCriterion("dest_latitude not like", value, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeIn(List<String> values) {
            addCriterion("dest_latitude in", values, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeNotIn(List<String> values) {
            addCriterion("dest_latitude not in", values, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeBetween(String value1, String value2) {
            addCriterion("dest_latitude between", value1, value2, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andDestLatitudeNotBetween(String value1, String value2) {
            addCriterion("dest_latitude not between", value1, value2, "destLatitude");
            return (Criteria) this;
        }

        public Criteria andEncryptIsNull() {
            addCriterion("encrypt is null");
            return (Criteria) this;
        }

        public Criteria andEncryptIsNotNull() {
            addCriterion("encrypt is not null");
            return (Criteria) this;
        }

        public Criteria andEncryptEqualTo(String value) {
            addCriterion("encrypt =", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptNotEqualTo(String value) {
            addCriterion("encrypt <>", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptGreaterThan(String value) {
            addCriterion("encrypt >", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptGreaterThanOrEqualTo(String value) {
            addCriterion("encrypt >=", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptLessThan(String value) {
            addCriterion("encrypt <", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptLessThanOrEqualTo(String value) {
            addCriterion("encrypt <=", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptLike(String value) {
            addCriterion("encrypt like", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptNotLike(String value) {
            addCriterion("encrypt not like", value, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptIn(List<String> values) {
            addCriterion("encrypt in", values, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptNotIn(List<String> values) {
            addCriterion("encrypt not in", values, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptBetween(String value1, String value2) {
            addCriterion("encrypt between", value1, value2, "encrypt");
            return (Criteria) this;
        }

        public Criteria andEncryptNotBetween(String value1, String value2) {
            addCriterion("encrypt not between", value1, value2, "encrypt");
            return (Criteria) this;
        }

        public Criteria andDepTimeIsNull() {
            addCriterion("dep_time is null");
            return (Criteria) this;
        }

        public Criteria andDepTimeIsNotNull() {
            addCriterion("dep_time is not null");
            return (Criteria) this;
        }

        public Criteria andDepTimeEqualTo(String value) {
            addCriterion("dep_time =", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeNotEqualTo(String value) {
            addCriterion("dep_time <>", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeGreaterThan(String value) {
            addCriterion("dep_time >", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeGreaterThanOrEqualTo(String value) {
            addCriterion("dep_time >=", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeLessThan(String value) {
            addCriterion("dep_time <", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeLessThanOrEqualTo(String value) {
            addCriterion("dep_time <=", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeLike(String value) {
            addCriterion("dep_time like", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeNotLike(String value) {
            addCriterion("dep_time not like", value, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeIn(List<String> values) {
            addCriterion("dep_time in", values, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeNotIn(List<String> values) {
            addCriterion("dep_time not in", values, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeBetween(String value1, String value2) {
            addCriterion("dep_time between", value1, value2, "depTime");
            return (Criteria) this;
        }

        public Criteria andDepTimeNotBetween(String value1, String value2) {
            addCriterion("dep_time not between", value1, value2, "depTime");
            return (Criteria) this;
        }

        public Criteria andDriverMileIsNull() {
            addCriterion("driver_mile is null");
            return (Criteria) this;
        }

        public Criteria andDriverMileIsNotNull() {
            addCriterion("driver_mile is not null");
            return (Criteria) this;
        }

        public Criteria andDriverMileEqualTo(String value) {
            addCriterion("driver_mile =", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileNotEqualTo(String value) {
            addCriterion("driver_mile <>", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileGreaterThan(String value) {
            addCriterion("driver_mile >", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileGreaterThanOrEqualTo(String value) {
            addCriterion("driver_mile >=", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileLessThan(String value) {
            addCriterion("driver_mile <", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileLessThanOrEqualTo(String value) {
            addCriterion("driver_mile <=", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileLike(String value) {
            addCriterion("driver_mile like", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileNotLike(String value) {
            addCriterion("driver_mile not like", value, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileIn(List<String> values) {
            addCriterion("driver_mile in", values, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileNotIn(List<String> values) {
            addCriterion("driver_mile not in", values, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileBetween(String value1, String value2) {
            addCriterion("driver_mile between", value1, value2, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverMileNotBetween(String value1, String value2) {
            addCriterion("driver_mile not between", value1, value2, "driverMile");
            return (Criteria) this;
        }

        public Criteria andDriverTimeIsNull() {
            addCriterion("driver_time is null");
            return (Criteria) this;
        }

        public Criteria andDriverTimeIsNotNull() {
            addCriterion("driver_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriverTimeEqualTo(String value) {
            addCriterion("driver_time =", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeNotEqualTo(String value) {
            addCriterion("driver_time <>", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeGreaterThan(String value) {
            addCriterion("driver_time >", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeGreaterThanOrEqualTo(String value) {
            addCriterion("driver_time >=", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeLessThan(String value) {
            addCriterion("driver_time <", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeLessThanOrEqualTo(String value) {
            addCriterion("driver_time <=", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeLike(String value) {
            addCriterion("driver_time like", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeNotLike(String value) {
            addCriterion("driver_time not like", value, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeIn(List<String> values) {
            addCriterion("driver_time in", values, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeNotIn(List<String> values) {
            addCriterion("driver_time not in", values, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeBetween(String value1, String value2) {
            addCriterion("driver_time between", value1, value2, "driverTime");
            return (Criteria) this;
        }

        public Criteria andDriverTimeNotBetween(String value1, String value2) {
            addCriterion("driver_time not between", value1, value2, "driverTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(String value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(String value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(String value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(String value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(String value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLike(String value) {
            addCriterion("create_time like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotLike(String value) {
            addCriterion("create_time not like", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<String> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<String> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(String value1, String value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(String value1, String value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(String value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(String value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(String value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(String value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(String value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(String value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLike(String value) {
            addCriterion("update_time like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotLike(String value) {
            addCriterion("update_time not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<String> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<String> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(String value1, String value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(String value1, String value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_arrive
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}