package com.gk.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_arrive
 */
public class Arrive {
    /**
     * Database Column Remarks:
     *   唯一标识符
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * Database Column Remarks:
     *   公司标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.version_no
     *
     * @mbg.generated
     */
    private Integer versionNo;

    /**
     * Database Column Remarks:
     *   批次号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     * Database Column Remarks:
     *   车辆到达经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.dest_longgitude
     *
     * @mbg.generated
     */
    private String destLonggitude;

    /**
     * Database Column Remarks:
     *   车辆到达纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.dest_latitude
     *
     * @mbg.generated
     */
    private String destLatitude;

    /**
     * Database Column Remarks:
     *   坐标加密标识,1:GCJ-02 测绘局标准，2:WGS84 GPS标准，3:BD-09 百度标准，4:CGCS2000 北斗标准呢，5:其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.encrypt
     *
     * @mbg.generated
     */
    private String encrypt;

    /**
     * Database Column Remarks:
     *   下车时间,YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.dep_time
     *
     * @mbg.generated
     */
    private String depTime;

    /**
     * Database Column Remarks:
     *   载客里程,单位：km
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.driver_mile
     *
     * @mbg.generated
     */
    private String driverMile;

    /**
     * Database Column Remarks:
     *   载客时间,单位：秒
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.driver_time
     *
     * @mbg.generated
     */
    private String driverTime;

    /**
     * Database Column Remarks:
     *   上报状态，0:待上报，1:上报中，2:上报成功，3：上报失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   添加时间，YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * Database Column Remarks:
     *   修改时间，YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_arrive.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.uuid
     *
     * @return the value of t_arrive.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.uuid
     *
     * @param uuid the value for t_arrive.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.company_id
     *
     * @return the value of t_arrive.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.company_id
     *
     * @param companyId the value for t_arrive.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.version_no
     *
     * @return the value of t_arrive.version_no
     *
     * @mbg.generated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.version_no
     *
     * @param versionNo the value for t_arrive.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.batch_no
     *
     * @return the value of t_arrive.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.batch_no
     *
     * @param batchNo the value for t_arrive.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.order_id
     *
     * @return the value of t_arrive.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.order_id
     *
     * @param orderId the value for t_arrive.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.dest_longgitude
     *
     * @return the value of t_arrive.dest_longgitude
     *
     * @mbg.generated
     */
    public String getDestLonggitude() {
        return destLonggitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.dest_longgitude
     *
     * @param destLonggitude the value for t_arrive.dest_longgitude
     *
     * @mbg.generated
     */
    public void setDestLonggitude(String destLonggitude) {
        this.destLonggitude = destLonggitude == null ? null : destLonggitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.dest_latitude
     *
     * @return the value of t_arrive.dest_latitude
     *
     * @mbg.generated
     */
    public String getDestLatitude() {
        return destLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.dest_latitude
     *
     * @param destLatitude the value for t_arrive.dest_latitude
     *
     * @mbg.generated
     */
    public void setDestLatitude(String destLatitude) {
        this.destLatitude = destLatitude == null ? null : destLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.encrypt
     *
     * @return the value of t_arrive.encrypt
     *
     * @mbg.generated
     */
    public String getEncrypt() {
        return encrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.encrypt
     *
     * @param encrypt the value for t_arrive.encrypt
     *
     * @mbg.generated
     */
    public void setEncrypt(String encrypt) {
        this.encrypt = encrypt == null ? null : encrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.dep_time
     *
     * @return the value of t_arrive.dep_time
     *
     * @mbg.generated
     */
    public String getDepTime() {
        return depTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.dep_time
     *
     * @param depTime the value for t_arrive.dep_time
     *
     * @mbg.generated
     */
    public void setDepTime(String depTime) {
        this.depTime = depTime == null ? null : depTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.driver_mile
     *
     * @return the value of t_arrive.driver_mile
     *
     * @mbg.generated
     */
    public String getDriverMile() {
        return driverMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.driver_mile
     *
     * @param driverMile the value for t_arrive.driver_mile
     *
     * @mbg.generated
     */
    public void setDriverMile(String driverMile) {
        this.driverMile = driverMile == null ? null : driverMile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.driver_time
     *
     * @return the value of t_arrive.driver_time
     *
     * @mbg.generated
     */
    public String getDriverTime() {
        return driverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.driver_time
     *
     * @param driverTime the value for t_arrive.driver_time
     *
     * @mbg.generated
     */
    public void setDriverTime(String driverTime) {
        this.driverTime = driverTime == null ? null : driverTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.status
     *
     * @return the value of t_arrive.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.status
     *
     * @param status the value for t_arrive.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.create_time
     *
     * @return the value of t_arrive.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.create_time
     *
     * @param createTime the value for t_arrive.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_arrive.update_time
     *
     * @return the value of t_arrive.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_arrive.update_time
     *
     * @param updateTime the value for t_arrive.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}