package com.gk.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_plivate_route
 */
public class PlivateRoute {
    /**
     * Database Column Remarks:
     *   唯一标识符
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * Database Column Remarks:
     *   公司标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.version_no
     *
     * @mbg.generated
     */
    private Integer versionNo;

    /**
     * Database Column Remarks:
     *   批次号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   行政区划代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   驾驶员发起行程编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.route_id
     *
     * @mbg.generated
     */
    private String routeId;

    /**
     * Database Column Remarks:
     *   驾驶员姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.driver_name
     *
     * @mbg.generated
     */
    private String driverName;

    /**
     * Database Column Remarks:
     *   驾驶员手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.driver_phone
     *
     * @mbg.generated
     */
    private String driverPhone;

    /**
     * Database Column Remarks:
     *   机动车驾驶证编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.license_id
     *
     * @mbg.generated
     */
    private String licenseId;

    /**
     * Database Column Remarks:
     *   车辆号牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.vehicle_no
     *
     * @mbg.generated
     */
    private String vehicleNo;

    /**
     * Database Column Remarks:
     *   行程出发地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.departure
     *
     * @mbg.generated
     */
    private String departure;

    /**
     * Database Column Remarks:
     *   车辆出发经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.dep_longgitude
     *
     * @mbg.generated
     */
    private String depLonggitude;

    /**
     * Database Column Remarks:
     *   车辆出发纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.dep_latitude
     *
     * @mbg.generated
     */
    private String depLatitude;

    /**
     * Database Column Remarks:
     *   行程到达地点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.destination
     *
     * @mbg.generated
     */
    private String destination;

    /**
     * Database Column Remarks:
     *   车辆到达经度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.dest_longgitude
     *
     * @mbg.generated
     */
    private String destLonggitude;

    /**
     * Database Column Remarks:
     *   车辆到达纬度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.dest_latitude
     *
     * @mbg.generated
     */
    private String destLatitude;

    /**
     * Database Column Remarks:
     *   坐标加密标识,1:GCJ-02 测绘局标准，2:WGS84 GPS标准，3:BD-09 百度标准，4:CGCS2000 北斗标准呢，5:其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.encrypt
     *
     * @mbg.generated
     */
    private String encrypt;

    /**
     * Database Column Remarks:
     *   行程发布时间,YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.route_create_time
     *
     * @mbg.generated
     */
    private String routeCreateTime;

    /**
     * Database Column Remarks:
     *   行程预计里程,单位：km
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.route_mile
     *
     * @mbg.generated
     */
    private String routeMile;

    /**
     * Database Column Remarks:
     *   行程备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.route_note
     *
     * @mbg.generated
     */
    private String routeNote;

    /**
     * Database Column Remarks:
     *   上报状态，0:待上报，1:上报中，2:上报成功，3：上报失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   添加时间，YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * Database Column Remarks:
     *   修改时间，YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_plivate_route.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.uuid
     *
     * @return the value of t_plivate_route.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.uuid
     *
     * @param uuid the value for t_plivate_route.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.company_id
     *
     * @return the value of t_plivate_route.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.company_id
     *
     * @param companyId the value for t_plivate_route.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.version_no
     *
     * @return the value of t_plivate_route.version_no
     *
     * @mbg.generated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.version_no
     *
     * @param versionNo the value for t_plivate_route.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.batch_no
     *
     * @return the value of t_plivate_route.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.batch_no
     *
     * @param batchNo the value for t_plivate_route.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.address
     *
     * @return the value of t_plivate_route.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.address
     *
     * @param address the value for t_plivate_route.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.route_id
     *
     * @return the value of t_plivate_route.route_id
     *
     * @mbg.generated
     */
    public String getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.route_id
     *
     * @param routeId the value for t_plivate_route.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(String routeId) {
        this.routeId = routeId == null ? null : routeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.driver_name
     *
     * @return the value of t_plivate_route.driver_name
     *
     * @mbg.generated
     */
    public String getDriverName() {
        return driverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.driver_name
     *
     * @param driverName the value for t_plivate_route.driver_name
     *
     * @mbg.generated
     */
    public void setDriverName(String driverName) {
        this.driverName = driverName == null ? null : driverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.driver_phone
     *
     * @return the value of t_plivate_route.driver_phone
     *
     * @mbg.generated
     */
    public String getDriverPhone() {
        return driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.driver_phone
     *
     * @param driverPhone the value for t_plivate_route.driver_phone
     *
     * @mbg.generated
     */
    public void setDriverPhone(String driverPhone) {
        this.driverPhone = driverPhone == null ? null : driverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.license_id
     *
     * @return the value of t_plivate_route.license_id
     *
     * @mbg.generated
     */
    public String getLicenseId() {
        return licenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.license_id
     *
     * @param licenseId the value for t_plivate_route.license_id
     *
     * @mbg.generated
     */
    public void setLicenseId(String licenseId) {
        this.licenseId = licenseId == null ? null : licenseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.vehicle_no
     *
     * @return the value of t_plivate_route.vehicle_no
     *
     * @mbg.generated
     */
    public String getVehicleNo() {
        return vehicleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.vehicle_no
     *
     * @param vehicleNo the value for t_plivate_route.vehicle_no
     *
     * @mbg.generated
     */
    public void setVehicleNo(String vehicleNo) {
        this.vehicleNo = vehicleNo == null ? null : vehicleNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.departure
     *
     * @return the value of t_plivate_route.departure
     *
     * @mbg.generated
     */
    public String getDeparture() {
        return departure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.departure
     *
     * @param departure the value for t_plivate_route.departure
     *
     * @mbg.generated
     */
    public void setDeparture(String departure) {
        this.departure = departure == null ? null : departure.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.dep_longgitude
     *
     * @return the value of t_plivate_route.dep_longgitude
     *
     * @mbg.generated
     */
    public String getDepLonggitude() {
        return depLonggitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.dep_longgitude
     *
     * @param depLonggitude the value for t_plivate_route.dep_longgitude
     *
     * @mbg.generated
     */
    public void setDepLonggitude(String depLonggitude) {
        this.depLonggitude = depLonggitude == null ? null : depLonggitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.dep_latitude
     *
     * @return the value of t_plivate_route.dep_latitude
     *
     * @mbg.generated
     */
    public String getDepLatitude() {
        return depLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.dep_latitude
     *
     * @param depLatitude the value for t_plivate_route.dep_latitude
     *
     * @mbg.generated
     */
    public void setDepLatitude(String depLatitude) {
        this.depLatitude = depLatitude == null ? null : depLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.destination
     *
     * @return the value of t_plivate_route.destination
     *
     * @mbg.generated
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.destination
     *
     * @param destination the value for t_plivate_route.destination
     *
     * @mbg.generated
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.dest_longgitude
     *
     * @return the value of t_plivate_route.dest_longgitude
     *
     * @mbg.generated
     */
    public String getDestLonggitude() {
        return destLonggitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.dest_longgitude
     *
     * @param destLonggitude the value for t_plivate_route.dest_longgitude
     *
     * @mbg.generated
     */
    public void setDestLonggitude(String destLonggitude) {
        this.destLonggitude = destLonggitude == null ? null : destLonggitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.dest_latitude
     *
     * @return the value of t_plivate_route.dest_latitude
     *
     * @mbg.generated
     */
    public String getDestLatitude() {
        return destLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.dest_latitude
     *
     * @param destLatitude the value for t_plivate_route.dest_latitude
     *
     * @mbg.generated
     */
    public void setDestLatitude(String destLatitude) {
        this.destLatitude = destLatitude == null ? null : destLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.encrypt
     *
     * @return the value of t_plivate_route.encrypt
     *
     * @mbg.generated
     */
    public String getEncrypt() {
        return encrypt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.encrypt
     *
     * @param encrypt the value for t_plivate_route.encrypt
     *
     * @mbg.generated
     */
    public void setEncrypt(String encrypt) {
        this.encrypt = encrypt == null ? null : encrypt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.route_create_time
     *
     * @return the value of t_plivate_route.route_create_time
     *
     * @mbg.generated
     */
    public String getRouteCreateTime() {
        return routeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.route_create_time
     *
     * @param routeCreateTime the value for t_plivate_route.route_create_time
     *
     * @mbg.generated
     */
    public void setRouteCreateTime(String routeCreateTime) {
        this.routeCreateTime = routeCreateTime == null ? null : routeCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.route_mile
     *
     * @return the value of t_plivate_route.route_mile
     *
     * @mbg.generated
     */
    public String getRouteMile() {
        return routeMile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.route_mile
     *
     * @param routeMile the value for t_plivate_route.route_mile
     *
     * @mbg.generated
     */
    public void setRouteMile(String routeMile) {
        this.routeMile = routeMile == null ? null : routeMile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.route_note
     *
     * @return the value of t_plivate_route.route_note
     *
     * @mbg.generated
     */
    public String getRouteNote() {
        return routeNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.route_note
     *
     * @param routeNote the value for t_plivate_route.route_note
     *
     * @mbg.generated
     */
    public void setRouteNote(String routeNote) {
        this.routeNote = routeNote == null ? null : routeNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.status
     *
     * @return the value of t_plivate_route.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.status
     *
     * @param status the value for t_plivate_route.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.create_time
     *
     * @return the value of t_plivate_route.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.create_time
     *
     * @param createTime the value for t_plivate_route.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_plivate_route.update_time
     *
     * @return the value of t_plivate_route.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_plivate_route.update_time
     *
     * @param updateTime the value for t_plivate_route.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}