package com.gk.model;

import java.util.ArrayList;
import java.util.List;

public class PositionGkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public PositionGkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andStartLonIsNull() {
            addCriterion("start_lon is null");
            return (Criteria) this;
        }

        public Criteria andStartLonIsNotNull() {
            addCriterion("start_lon is not null");
            return (Criteria) this;
        }

        public Criteria andStartLonEqualTo(String value) {
            addCriterion("start_lon =", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonNotEqualTo(String value) {
            addCriterion("start_lon <>", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonGreaterThan(String value) {
            addCriterion("start_lon >", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonGreaterThanOrEqualTo(String value) {
            addCriterion("start_lon >=", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonLessThan(String value) {
            addCriterion("start_lon <", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonLessThanOrEqualTo(String value) {
            addCriterion("start_lon <=", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonLike(String value) {
            addCriterion("start_lon like", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonNotLike(String value) {
            addCriterion("start_lon not like", value, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonIn(List<String> values) {
            addCriterion("start_lon in", values, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonNotIn(List<String> values) {
            addCriterion("start_lon not in", values, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonBetween(String value1, String value2) {
            addCriterion("start_lon between", value1, value2, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLonNotBetween(String value1, String value2) {
            addCriterion("start_lon not between", value1, value2, "startLon");
            return (Criteria) this;
        }

        public Criteria andStartLatIsNull() {
            addCriterion("start_lat is null");
            return (Criteria) this;
        }

        public Criteria andStartLatIsNotNull() {
            addCriterion("start_lat is not null");
            return (Criteria) this;
        }

        public Criteria andStartLatEqualTo(String value) {
            addCriterion("start_lat =", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotEqualTo(String value) {
            addCriterion("start_lat <>", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatGreaterThan(String value) {
            addCriterion("start_lat >", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatGreaterThanOrEqualTo(String value) {
            addCriterion("start_lat >=", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatLessThan(String value) {
            addCriterion("start_lat <", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatLessThanOrEqualTo(String value) {
            addCriterion("start_lat <=", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatLike(String value) {
            addCriterion("start_lat like", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotLike(String value) {
            addCriterion("start_lat not like", value, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatIn(List<String> values) {
            addCriterion("start_lat in", values, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotIn(List<String> values) {
            addCriterion("start_lat not in", values, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatBetween(String value1, String value2) {
            addCriterion("start_lat between", value1, value2, "startLat");
            return (Criteria) this;
        }

        public Criteria andStartLatNotBetween(String value1, String value2) {
            addCriterion("start_lat not between", value1, value2, "startLat");
            return (Criteria) this;
        }

        public Criteria andEndLonIsNull() {
            addCriterion("end_lon is null");
            return (Criteria) this;
        }

        public Criteria andEndLonIsNotNull() {
            addCriterion("end_lon is not null");
            return (Criteria) this;
        }

        public Criteria andEndLonEqualTo(String value) {
            addCriterion("end_lon =", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonNotEqualTo(String value) {
            addCriterion("end_lon <>", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonGreaterThan(String value) {
            addCriterion("end_lon >", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonGreaterThanOrEqualTo(String value) {
            addCriterion("end_lon >=", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonLessThan(String value) {
            addCriterion("end_lon <", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonLessThanOrEqualTo(String value) {
            addCriterion("end_lon <=", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonLike(String value) {
            addCriterion("end_lon like", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonNotLike(String value) {
            addCriterion("end_lon not like", value, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonIn(List<String> values) {
            addCriterion("end_lon in", values, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonNotIn(List<String> values) {
            addCriterion("end_lon not in", values, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonBetween(String value1, String value2) {
            addCriterion("end_lon between", value1, value2, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLonNotBetween(String value1, String value2) {
            addCriterion("end_lon not between", value1, value2, "endLon");
            return (Criteria) this;
        }

        public Criteria andEndLatIsNull() {
            addCriterion("end_lat is null");
            return (Criteria) this;
        }

        public Criteria andEndLatIsNotNull() {
            addCriterion("end_lat is not null");
            return (Criteria) this;
        }

        public Criteria andEndLatEqualTo(String value) {
            addCriterion("end_lat =", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotEqualTo(String value) {
            addCriterion("end_lat <>", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatGreaterThan(String value) {
            addCriterion("end_lat >", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatGreaterThanOrEqualTo(String value) {
            addCriterion("end_lat >=", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatLessThan(String value) {
            addCriterion("end_lat <", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatLessThanOrEqualTo(String value) {
            addCriterion("end_lat <=", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatLike(String value) {
            addCriterion("end_lat like", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotLike(String value) {
            addCriterion("end_lat not like", value, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatIn(List<String> values) {
            addCriterion("end_lat in", values, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotIn(List<String> values) {
            addCriterion("end_lat not in", values, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatBetween(String value1, String value2) {
            addCriterion("end_lat between", value1, value2, "endLat");
            return (Criteria) this;
        }

        public Criteria andEndLatNotBetween(String value1, String value2) {
            addCriterion("end_lat not between", value1, value2, "endLat");
            return (Criteria) this;
        }

        public Criteria andInstantLonIsNull() {
            addCriterion("instant_lon is null");
            return (Criteria) this;
        }

        public Criteria andInstantLonIsNotNull() {
            addCriterion("instant_lon is not null");
            return (Criteria) this;
        }

        public Criteria andInstantLonEqualTo(String value) {
            addCriterion("instant_lon =", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonNotEqualTo(String value) {
            addCriterion("instant_lon <>", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonGreaterThan(String value) {
            addCriterion("instant_lon >", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonGreaterThanOrEqualTo(String value) {
            addCriterion("instant_lon >=", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonLessThan(String value) {
            addCriterion("instant_lon <", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonLessThanOrEqualTo(String value) {
            addCriterion("instant_lon <=", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonLike(String value) {
            addCriterion("instant_lon like", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonNotLike(String value) {
            addCriterion("instant_lon not like", value, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonIn(List<String> values) {
            addCriterion("instant_lon in", values, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonNotIn(List<String> values) {
            addCriterion("instant_lon not in", values, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonBetween(String value1, String value2) {
            addCriterion("instant_lon between", value1, value2, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLonNotBetween(String value1, String value2) {
            addCriterion("instant_lon not between", value1, value2, "instantLon");
            return (Criteria) this;
        }

        public Criteria andInstantLatIsNull() {
            addCriterion("instant_lat is null");
            return (Criteria) this;
        }

        public Criteria andInstantLatIsNotNull() {
            addCriterion("instant_lat is not null");
            return (Criteria) this;
        }

        public Criteria andInstantLatEqualTo(String value) {
            addCriterion("instant_lat =", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatNotEqualTo(String value) {
            addCriterion("instant_lat <>", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatGreaterThan(String value) {
            addCriterion("instant_lat >", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatGreaterThanOrEqualTo(String value) {
            addCriterion("instant_lat >=", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatLessThan(String value) {
            addCriterion("instant_lat <", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatLessThanOrEqualTo(String value) {
            addCriterion("instant_lat <=", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatLike(String value) {
            addCriterion("instant_lat like", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatNotLike(String value) {
            addCriterion("instant_lat not like", value, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatIn(List<String> values) {
            addCriterion("instant_lat in", values, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatNotIn(List<String> values) {
            addCriterion("instant_lat not in", values, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatBetween(String value1, String value2) {
            addCriterion("instant_lat between", value1, value2, "instantLat");
            return (Criteria) this;
        }

        public Criteria andInstantLatNotBetween(String value1, String value2) {
            addCriterion("instant_lat not between", value1, value2, "instantLat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_position_gk
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_position_gk
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}