package com.gk.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_terminal
 */
public class Terminal {
    /**
     * Database Column Remarks:
     *   唯一标识符
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     * Database Column Remarks:
     *   公司标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.version_no
     *
     * @mbg.generated
     */
    private Integer versionNo;

    /**
     * Database Column Remarks:
     *   批次号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.batch_no
     *
     * @mbg.generated
     */
    private String batchNo;

    /**
     * Database Column Remarks:
     *   行政区划代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   机动车驾驶证号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.license_id
     *
     * @mbg.generated
     */
    private String licenseId;

    /**
     * Database Column Remarks:
     *   驾驶员手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.driver_phone
     *
     * @mbg.generated
     */
    private String driverPhone;

    /**
     * Database Column Remarks:
     *   手机运营商,1:中国联通，2:中国移动，3:中国电信，4:其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.net_type
     *
     * @mbg.generated
     */
    private String netType;

    /**
     * Database Column Remarks:
     *   使用APP版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.app_version
     *
     * @mbg.generated
     */
    private String appVersion;

    /**
     * Database Column Remarks:
     *   使用地图类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.map_type
     *
     * @mbg.generated
     */
    private String mapType;

    /**
     * Database Column Remarks:
     *   状态，0:有效，1:无效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     * Database Column Remarks:
     *   操作标识，1:新增，2:更新，3:删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.flag
     *
     * @mbg.generated
     */
    private String flag;

    /**
     * Database Column Remarks:
     *   上报状态，0:待上报，1:上报中，2:上报成功，3：上报失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   添加时间，YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * Database Column Remarks:
     *   修改时间，YYYYMMDDhhmmss
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_terminal.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.uuid
     *
     * @return the value of t_terminal.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.uuid
     *
     * @param uuid the value for t_terminal.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.company_id
     *
     * @return the value of t_terminal.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.company_id
     *
     * @param companyId the value for t_terminal.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.version_no
     *
     * @return the value of t_terminal.version_no
     *
     * @mbg.generated
     */
    public Integer getVersionNo() {
        return versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.version_no
     *
     * @param versionNo the value for t_terminal.version_no
     *
     * @mbg.generated
     */
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.batch_no
     *
     * @return the value of t_terminal.batch_no
     *
     * @mbg.generated
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.batch_no
     *
     * @param batchNo the value for t_terminal.batch_no
     *
     * @mbg.generated
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.address
     *
     * @return the value of t_terminal.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.address
     *
     * @param address the value for t_terminal.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.license_id
     *
     * @return the value of t_terminal.license_id
     *
     * @mbg.generated
     */
    public String getLicenseId() {
        return licenseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.license_id
     *
     * @param licenseId the value for t_terminal.license_id
     *
     * @mbg.generated
     */
    public void setLicenseId(String licenseId) {
        this.licenseId = licenseId == null ? null : licenseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.driver_phone
     *
     * @return the value of t_terminal.driver_phone
     *
     * @mbg.generated
     */
    public String getDriverPhone() {
        return driverPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.driver_phone
     *
     * @param driverPhone the value for t_terminal.driver_phone
     *
     * @mbg.generated
     */
    public void setDriverPhone(String driverPhone) {
        this.driverPhone = driverPhone == null ? null : driverPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.net_type
     *
     * @return the value of t_terminal.net_type
     *
     * @mbg.generated
     */
    public String getNetType() {
        return netType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.net_type
     *
     * @param netType the value for t_terminal.net_type
     *
     * @mbg.generated
     */
    public void setNetType(String netType) {
        this.netType = netType == null ? null : netType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.app_version
     *
     * @return the value of t_terminal.app_version
     *
     * @mbg.generated
     */
    public String getAppVersion() {
        return appVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.app_version
     *
     * @param appVersion the value for t_terminal.app_version
     *
     * @mbg.generated
     */
    public void setAppVersion(String appVersion) {
        this.appVersion = appVersion == null ? null : appVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.map_type
     *
     * @return the value of t_terminal.map_type
     *
     * @mbg.generated
     */
    public String getMapType() {
        return mapType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.map_type
     *
     * @param mapType the value for t_terminal.map_type
     *
     * @mbg.generated
     */
    public void setMapType(String mapType) {
        this.mapType = mapType == null ? null : mapType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.state
     *
     * @return the value of t_terminal.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.state
     *
     * @param state the value for t_terminal.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.flag
     *
     * @return the value of t_terminal.flag
     *
     * @mbg.generated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.flag
     *
     * @param flag the value for t_terminal.flag
     *
     * @mbg.generated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.status
     *
     * @return the value of t_terminal.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.status
     *
     * @param status the value for t_terminal.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.create_time
     *
     * @return the value of t_terminal.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.create_time
     *
     * @param createTime the value for t_terminal.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_terminal.update_time
     *
     * @return the value of t_terminal.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_terminal.update_time
     *
     * @param updateTime the value for t_terminal.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}