package com.gk.mapper;

import com.gk.model.Arrive;
import com.gk.model.ArriveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArriveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    long countByExample(ArriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int deleteByExample(ArriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int insert(Arrive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int insertSelective(Arrive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    List<Arrive> selectByExample(ArriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    Arrive selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Arrive record, @Param("example") ArriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Arrive record, @Param("example") ArriveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Arrive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_arrive
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Arrive record);
}