package com.gk.mapper;

import com.gk.model.Depart;
import com.gk.model.DepartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    long countByExample(DepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int deleteByExample(DepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int insert(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int insertSelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    List<Depart> selectByExample(DepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    Depart selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Depart record, @Param("example") DepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Depart record, @Param("example") DepartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_depart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Depart record);
}