package com.gk.mapper;

import com.gk.model.OrderStart;
import com.gk.model.OrderStartExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrderStartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    long countByExample(OrderStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int deleteByExample(OrderStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int insert(OrderStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int insertSelective(OrderStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    List<OrderStart> selectByExample(OrderStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    OrderStart selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderStart record, @Param("example") OrderStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderStart record, @Param("example") OrderStartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderStart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_start
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderStart record);
    
    /**
     * 
     * @return
     */
    public List<Map<String, Object>> getOrderInfoList();
}