package com.gk.mapper;

import com.gk.model.OrderSucces;
import com.gk.model.OrderSuccesExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OrderSuccesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    long countByExample(OrderSuccesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int deleteByExample(OrderSuccesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int insert(OrderSucces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int insertSelective(OrderSucces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    List<OrderSucces> selectByExample(OrderSuccesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    OrderSucces selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrderSucces record, @Param("example") OrderSuccesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrderSucces record, @Param("example") OrderSuccesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderSucces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_succes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderSucces record);
    
    /**
     * 
     * @param orderId
     * @return
     */
    public List<Map<String, Object>> getRouteInfoList(String orderId);
}