package com.gk.mapper;

import com.gk.model.PlivateOrder;
import com.gk.model.PlivateOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlivateOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    long countByExample(PlivateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int deleteByExample(PlivateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int insert(PlivateOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int insertSelective(PlivateOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    List<PlivateOrder> selectByExample(PlivateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    PlivateOrder selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlivateOrder record, @Param("example") PlivateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlivateOrder record, @Param("example") PlivateOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlivateOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_plivate_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlivateOrder record);
}