package com.gk.mapper;

import com.gk.model.Terminal;
import com.gk.model.TerminalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TerminalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    long countByExample(TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int deleteByExample(TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int insert(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int insertSelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    List<Terminal> selectByExample(TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    Terminal selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Terminal record, @Param("example") TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Terminal record, @Param("example") TerminalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Terminal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_terminal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Terminal record);
}